services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8200:80
    depends_on:
      - db
