import {
  BookOpen,
  Upload,
  Trophy,
  Layers,
  UserCog,
  UserCheck,
  Users,
  LogOut,
  Menu,
  X,
  Square,
  SquareCheck,
  EllipsisVertical,
  Edit,
  Trash,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Search,
} from "lucide-react";

export const icons = {
  'upload': Upload,
  'trophy': Trophy,
  'layers': Layers,
  'userCog': UserCog,
  'userCheck': UserCheck,
  'users': Users,
  'logOut': LogOut,
  'menu': Menu,
  'x': X,
  'book-open': BookOpen,
  'square': Square,
  'square-check': SquareCheck,
  'ellipsis-vertical': EllipsisVertical,
  'edit': Edit,
  'trash': Trash,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'search': Search,
} as const;

export type IconName = keyof typeof icons;